name: safenet_vpn
description: SafeNet VPN - Stealth bypass for censored regions
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State
  provider: ^6.1.2

  # Network
  dio: ^5.4.3
  connectivity_plus: ^6.0.3

  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2

  # Device
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2

  # UI
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  shimmer: ^3.0.0

  # Utils
  uuid: ^4.4.2
  intl: ^0.19.0
  url_launcher: ^6.3.0
  qr_flutter: ^4.1.0
  share_plus: ^10.0.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/animations/
    # assets/singbox/  # Iran build only (build_iran.ps1)
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
